[workspace]
resolver = "1"
members = [
    "cli",
    "utils",
    "network",
    "protocol",
    "acss",
    "crypto",
    "benches",
]

default-members = ["cli"]

[profile.release]
# debug = true
lto = true
